language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
env:
  global:
  - secure: YPD9HWtwPZhIt50HQphVZ02jb4UB6+nFeJ9XbBY7tzZ66xEK55ufYYWo2sHGzgk5huktIZMW11kqrHlCt9Z92AfWTi1Nq9z5lOmSGGFrrN1LKMEF30UMpymqaWSc3p/vvyADYp/RH66dJmE/5pS3Mmk1V4NIPT/rClQfYaf6JYU=
  - secure: CZ955IbUkJ+WenIc9Q8EaCWOEovXgh5e72rbQCs3ZNpOI1iE84IDDiV14ahatQXdCSTX4SPJ7pLDYzTwrg8gERe2ESLKz6EUnQRDJJvpf6BCl7nfs+wMlEAuh9KySjt6FkQmq/SCAzCxv7LHDoQFnoWFaveiAVCHeDDnF5Sr9v8=
